### PR TITLE
fix unmarshaling null into []byte

### LINKED ISSUE #40: Can't round trip nil slice
```go
package main

import (
	"github.com/polydawn/refmt/cbor"
	"github.com/polydawn/refmt/obj/atlas"
)

type Thing struct {
	Array []byte
}

func main() {
	atlas := atlas.MustBuild(
		atlas.BuildEntry(Thing{}).StructMap().Autogenerate().Complete(),
	)

	b, err := cbor.MarshalAtlased(Thing{}, atlas)
	if err != nil {
		panic(err)
	}

	var t Thing
	err = cbor.UnmarshalAtlased(b, &t, atlas)
	if err != nil {
		panic(err) // fails here.
	}
}
```

### PR DESCRIPTION
**Pull request by Stebalien**
fixes #40

### CODE REVIEW

File: obj/unmarshalBuiltins.go [hunk 1]
```diff
@@ -138,6 +141,12 @@ func (mach *unmarshalMachinePrimitive) Step(_ *Unmarshaller, _ *unmarshalSlab, t
 				mach.rv.Index(i).SetUint(uint64(tok.Bytes[i]))
 			}
 			return true, nil
+		case TNull:
```
Comment (Stebalien) [inline obj/unmarshalBuiltins.go]: Maybe not needed but this matches the behavior of `[N]int`.
